Conserta o período de extração da spider do senado
cuducos/raspadorlegislativo pull request #10
Opened 2022-07-22 16:56 UTC by arielbello

A versão atual da spider do senado só extrai os dados do ano configurado em `START_DATE` no `.env`. Essa PR conserta isso criando uma request para cada ano, a partir do `START_DATE` até a data atual.

2022-07-26 17:17 UTC, cuducos requested changes

2022-07-26 17:17 UTC, cuducos commented on .gitignore
> +.idea/
Isso é uma cofniguração do usuário, não do projeto. Acredito que apenas coisas relacionadas ao projeto devam estar no repositório. Você, se quiser, pode criar um [`.gitignore` global para seu usário](https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/), mas acho que isso não pertence ao projeto ; )

2022-07-26 17:17 UTC, cuducos commented on raspadorlegislativo/spiders/senado.py
> +        for date_parameter in self.date_parameters(date.fromisoformat(settings.START_DATE)):
Acho que estamos fazendo  conversões desnecessárias: aqui, de `str` para `date`; na  linha 34: de `date` de volta para `str`. Precisamos dessas duas conversões?

2022-07-26 17:17 UTC, cuducos commented on raspadorlegislativo/spiders/senado.py
> +        formatted_start_date = start_date.isoformat().replace('-', '')
Não seria mais claro usar o `.strftime`? Na minha opinião, seria, pois nunca lembro de cabeça qual é o formato ISO, mas isso é só opinião hehehe…

2022-07-26 17:17 UTC, cuducos commented on raspadorlegislativo/spiders/senado.py
> +        return [formatted_start_date] + [f"{year}0101" for year in range(start_date.year + 1, date.today().year + 1)]
Duas sugestões:
1. [Não precisamos de uma lista](https://cuducos.me/2018/06/13/tuplas-e-listas-no-python.html), podemos ter um [gerador](https://cuducos.me/2017/08/11/geradores-do-python-o-que-sao-e-quais-problemas-resolvem.html)
2. Para manipular datas, é melhor e mais seguro usar o objeto `date` do que manipular _strings_

```suggestion
        yield start_date
        yield from (date(year, 1, 1) for year in range(start_date.year + 1, date.today().year + 1))
```

2022-07-26 17:17 UTC, cuducos commented on raspadorlegislativo/spiders/senado.py
> +                yield Request(url=url)
Sugestão nada importante:

```suggestion
            yield from (Request(url=self.urls['list'].format(s, date_parameter)) for s in self.subjects)
```

2022-07-27 19:42 UTC, arielbello commented on raspadorlegislativo/spiders/senado.py
> +        formatted_start_date = start_date.isoformat().replace('-', '')
O iso pra mim é o mais fácil, mas strftime economiza uma função, então eu concordo que simplifica

2022-07-27 19:42 UTC, arielbello commented on raspadorlegislativo/spiders/senado.py
> +        formatted_start_date = start_date.isoformat().replace('-', '')
inclusive, tive que olhar aqui a documentação pra lembrar qual letra quer dizer oq no `strftime` :rofl:

2022-07-27 19:52 UTC, cuducos commented on raspadorlegislativo/spiders/senado.py
> +        formatted_start_date = start_date.isoformat().replace('-', '')
Hahaha… tranquilo. FIque à vontade para escolher o que achar melhor : )

2022-07-27 20:45 UTC, cuducos reviewed
Algum motivo especial para manipular datas como `str` ao invés de `date`?

2022-07-27 21:07 UTC, arielbello commented
> Algum motivo especial para manipular datas como `str` ao invés de `date`?

Tá se referindo especificamente a essa [linha](https://github.com/cuducos/raspadorlegislativo/pull/10/files#diff-0376dbe6ae262179bbbb4ac721ab687c13f6cf186220be2ba2d37f48ca842025R36) do commit anterior?

2022-07-27 21:38 UTC, cuducos reviewed
Algumas coisas ainda me incomodam nessa implementação:

- a lógica do `date_parameters` parece pertecer ao `start_requests`
- o `date_parameters` recebe um argumento que é uma constante
- fazemos formtação de data em dois lugares distintos (linhas 34 e 36)

Isso me parece dizer que a implementação pode ser simplificada.

Que tal algo com (pseudo-código, não testei):

```python

    def start_requests(self):
        start_date = date.fromisoformat(settings.START_DATE)  # apenas uma transformação str -> date
        years = range(start_date.year, date.today().year + 1)
        dates = (date(year, 1, 1) for year in years)
        for subject, start_at in  product(self.subjects, dates):  # from itertools import product
            if start_at.year = start_date.year:
                start_at = start_date
            yield Request(url=url.format(subject, start_at.strftime("%Y%m%d")) #  apenas uma conversão date -> str  
```

Enfim… não precisa seguir essa implementação. Mas é só um exemplo de como eu lidaria com os três pontos levantados ali ; )

2022-07-28 00:56 UTC, cuducos approved these changes
Perfeito! Que tal fazer um rebase juntando esses _commits_ num só antes de eu fazer o merge?

2022-07-28 01:16 UTC, arielbello commented
> Perfeito! Que tal fazer um rebase juntando esses _commits_ num só antes de eu fazer o merge?

Não é mais fácil fazer um squas merge?

2022-07-28 02:18 UTC, merged